**data analysis packages**
- pandas for data frame:read and write operations
- numpy :numerical python,math operations
- matplotlib :plots,graphs:visualization
- seaborn :plots
- plotly:plots
- bokhe:plots


**machine learning package**
- sickit learn(sklearn) ===== model development
- stats packages === linear regression 

**webscrapping and database connection**
- sqlite ===== sql connection
- beautiful soup ==== scrape the data
- websocket ===== scrap the data
  

**deep learning packages**
- tensorflow === deep learning models development(google)
- keras
- pytorch === develop the facebook(meta)
- opencv ==== computer vision (reading and writing images)
- pillow === reading images

**NLP**
- NLTK === natural language tool kit
- spaCy  === nlp models
- worldcloud

**web development -API**
- Flask
- Django
- Fast API
- Gradio
  

**Apps Creation**
- streamlit

**Transformers BERT**
- transformers === Huggingface(Google)
 
==============pretrained models object detection=============
- vgg16
- Mobilenet
- Yolo ---- ultralytics

`**NLP Pretrained Models**
- Word2Vec === google
- Glove ==== StandforUniversity

**model save**
- pickle
-  Joblib

**GenAI LLM**
- Azure openAI
- Google Gemini
- Amazon BedRock
- LLAMA Meta AI
- Langchain Framework


**model deployment**
- Mlflow

**cloud Services**
- Azure ml related packages
- GCP vertax ai packages
- Amazon sagemaker packages

**Alle NLP**
- Allen NLP Packages

**ML Using Pyspark**
- MLLib package

**step1 : import the packages**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

 **step-2 :create a DataFrame using list**

In [5]:
import pandas as pd
data=pd.DataFrame()
#we created a data frame but no data(no rows and no columns)
#we saved our data frame with a name 'data'
data

Empty DataFrame
Columns: []
Index: []

**step3: provide the data**

In [3]:
name=['Raj','Abhi','Chinna']
pd.DataFrame(name)

0
0     Raj
1    Abhi
2  Chinna

In [32]:
name=['Raj','Abhi','Chinna']
age=[21,22,23]
pd.DataFrame(zip(name,age))

0   1
0     Raj  21
1    Abhi  22
2  Chinna  23

In [34]:
name=['Raj','Abhi','Chinna']
age=[21,22,23]
city=['hyd','chennai','mumbai']
pd.DataFrame(zip(name,age,city))

0   1        2
0     Raj  21      hyd
1    Abhi  22  chennai
2  Chinna  23   mumbai

In [36]:
name=['Raj','Abhi','Chinna']
age=[21,22,23]
city=['hyd','chennai','mumbai']
data=[name,age,city]
pd.DataFrame(data)

0        1       2
0  Raj     Abhi  Chinna
1   21       22      23
2  hyd  chennai  mumbai

In [7]:
name=['Raj','Abhi','Chinna']
age=[21,22,23]
city=['hyd','chennai','mumbai']
df=pd.DataFrame(zip(name,age,city))
df

0   1        2
0     Raj  21      hyd
1    Abhi  22  chennai
2  Chinna  23   mumbai

**step-4:provide the columns**
- columns we need to provide in a list
- the number of columns exactly match with data
- here we have 3 columns, so we need to create a list with 3 names

In [5]:
name=['Raj','Abhi','Chinna']
age=[21,22,23]
city=['hyd','chennai','mumbai']
cols=['Names','Age','City']
df=pd.DataFrame(zip(name,age,city),columns=cols)
df

Names  Age     City
0     Raj   21      hyd
1    Abhi   22  chennai
2  Chinna   23   mumbai

**step5:provide the index**

In [7]:
name=['Raj','Abhi','Chinna']
age=[21,22,23]
city=['hyd','chennai','mumbai']
idx=['a','b','c']
cols=['Names','Age','City']
df=pd.DataFrame(zip(name,age,city), index=idx,columns=cols)
df

Names  Age     City
a     Raj   21      hyd
b    Abhi   22  chennai
c  Chinna   23   mumbai

**step-6:how to add a new column already to existed dataframe**
- here we already has a dataframe with name **df**
- it has 3 columns
- now we want to add a new column **marks**
- we need to create a new array or list
- that length of list should equal to len of rows
- so here we have 3 rows,so new list also have 3 values

In [ ]:
#df['new column name']=<list>

In [9]:
marks=[100,200,300]
df['marks']=marks
df

Names  Age     City  marks
a     Raj   21      hyd    100
b    Abhi   22  chennai    200
c  Chinna   23   mumbai    300

In [13]:
import pandas as pd
names=['kusuma','vaish','teja']
ages=[21,22,23]
city=['hyd','chennai','mumbai']
ind=[1,2,3]
cols=['Names','ages','City']
data=pd.DataFrame(zip(names,ages,city),index=ind,columns=cols)
data


Names  ages     City
1  kusuma    21      hyd
2   vaish    22  chennai
3    teja    23   mumbai

In [15]:
data['marks']=[100,200,300]
data

Names  ages     City  marks
1  kusuma    21      hyd    100
2   vaish    22  chennai    200
3    teja    23   mumbai    300

**step7-Create a data frame using an empty dataframe**
- in above case we created a list
- we created a data frame by passing the list inside


In [28]:
#dataframe is created
df1=pd.DataFrame()
df1

Empty DataFrame
Columns: []
Index: []

In [36]:
#here no need to specify a column specifically
name=['Raj','Abhi','Chinna']
age=[21,22,23]
city=['hyd','chennai','mumbai']
df1['Name']=name
df1['Age']=age
df1['City']=city
df1


Name  Age     City
0     Raj   21      hyd
1    Abhi   22  chennai
2  Chinna   23   mumbai

**step8- create a dataframe using dictionary**

In [7]:
Name={'ramesh':21,'Suresh':22,'mahesh':23}
age={21,22,23}
data=pd.DataFrame(zip(Name,age),columns=['Name','age'])
data


Name  age
0  ramesh   21
1  Suresh   22
2  mahesh   23

In [47]:
dict1={'name':['Raj','Abhi','Chinna'],
        'age':[21,22,23],
        'city':['hyd','chennai','mumbai']}
dict1

{'name': ['Raj', 'Abhi', 'Chinna'],
 'age': [21, 22, 23],
 'city': ['hyd', 'chennai', 'mumbai']}

In [51]:
df2=pd.DataFrame(dict1)
df2

name  age     city
0     Raj   21      hyd
1    Abhi   22  chennai
2  Chinna   23   mumbai

- keys behave as columns
- values behave as rows


In [66]:
dict1={'name':'raj',
       'age':21,
       'city':'hyd'}
pd.DataFrame(dict1,index=[1])

name  age city
1  raj   21  hyd

- data in the form of array
    - list:normal way
    - numpy:numpy package
    - tensor:tensorflow

In [69]:
l1=[1,2,3]
import numpy as np
np.array(l1)
#tensor([1,2,3])

array([1, 2, 3])

In [75]:
l1=[1,2,3]
l2=[4,5,6]
l1+l2


[1, 2, 3, 4, 5, 6]

In [79]:
l1=[1,2,3]
a=np.array(l1)
l2=[4,5,6]
b=np.array(l2)
a+b
#sum of the two lists

array([5, 7, 9])

**step-9:dropping the column**
- in order to drop a column we need to use **drop** method
- all the methods based on your dataframe name similar as string names
- it requires mainly 3 arguments
    - 1.column name
    - 2.axis
        - axis=1 represents column
        - axis =0 represents rows
   
    - 3.inplace

        - once you drop the column,the dataframe affected
        - the modified dataframe want to save in a same name or different name
        - if we want to keep at a same name **inplace=True**     

In [208]:
name=['raj','chinna','abhi']
age=[21,22,23]
city=['hyd','che','mum']
df=pd.DataFrame(zip(name,age,city),index=[1,2,3],columns=['Name','Age','city'])
df.drop(columns=['city'],axis=1)

Name  Age
1     raj   21
2  chinna   22
3    abhi   23

In [1]:
name=['raj','chinna','abhi']
age=[21,22,23]
city=['hyd','che','mum']
df=pd.DataFrame(zip(name,age,city),index=[1,2,3],columns=['Name','Age','city'])
df.drop(index=[1],axis=1,inplace=True)

NameError: name 'pd' is not defined

In [149]:
name=['raj','chinna','abhi']
age=[21,22,23]
city=['hyd','che','mum']
df=pd.DataFrame(zip(name,age,city),index=[1,2,3],columns=['Name','Age','city'])
df.drop(index=[1],axis=0,inplace=True)
df

Name  Age city
2  chinna   22  che
3    abhi   23  mum

In [212]:
df.drop('city',axis=1,inplace=True)
df

Name  Age
1     raj   21
2  chinna   22
3    abhi   23

In [ ]:
#create two dataframes df1,df2 add those data frames


**step-10:how to overwrite existed column data**
- we already has a dataframe
- now we want replace all the values of a specified column with new values
- first create a list with new values
- then update the column with new values ,in the same way of how to create a new coloumn
- df[new col]=data, to create a new coloumn
- df[old col]=new data, to overwrite the old column

In [164]:
name=['raj','chinna','abhi']
age=[21,22,23]
city=['hyd','che','mum']
df=pd.DataFrame(zip(name,age,city),index=[1,2,3],columns=['Name','Age','city'])
df

Name  Age city
1     raj   21  hyd
2  chinna   22  che
3    abhi   23  mum

In [166]:
df['marks']=[100,200,300]
df

Name  Age city  marks
1     raj   21  hyd    100
2  chinna   22  che    200
3    abhi   23  mum    300

In [168]:
df['city']=['che','mum','hyd']
df

Name  Age city  marks
1     raj   21  che    100
2  chinna   22  mum    200
3    abhi   23  hyd    300

In [170]:
df['city']=['hyd','hyd','hyd']
df

Name  Age city  marks
1     raj   21  hyd    100
2  chinna   22  hyd    200
3    abhi   23  hyd    300

**step-11:how to save the data frame**
- we can save the dataframe using two ways
- csv:comma seperated value
- excel
- for csv : .to_csv          extension=.csv
- for excel: to_excel         extension=.xlsx

In [174]:
#create a dataframe
name=['raj','chinna','abhi']
age=[21,22,23]
city=['hyd','che','mum']
df=pd.DataFrame(zip(name,age,city),index=[1,2,3],columns=['Name','Age','city'])
df

Name  Age city
1     raj   21  hyd
2  chinna   22  che
3    abhi   23  mum

**csv format**

In [182]:
#dataframename.methodname
#where you want to save
#in what name you want to save
df.to_csv('data.csv')

In [184]:
df.to_excel('data.xlsx')

**step12-read the data**
- read_csv
    - read_excel
    - both available in pandas

In [189]:
pd.read_csv('data.csv')

Unnamed: 0    Name  Age city
0           1     raj   21  hyd
1           2  chinna   22  che
2           3    abhi   23  mum

In [191]:
pd.read_excel('data.xlsx')

Unnamed: 0    Name  Age city
0           1     raj   21  hyd
1           2  chinna   22  che
2           3    abhi   23  mum

**step-13:how to avoid extra column**
- while we are saving the data, we have argument name **index**
- keep index=False

In [194]:
#give the different name provide index=False
df.to_csv('data1.csv',index=False)

In [198]:
pd.read_csv('data1.csv')

Name  Age city
0     raj   21  hyd
1  chinna   22  che
2    abhi   23  mum

In [256]:
#create two dataframes df1,df2 add those data frames
name=['ramesh']
age=[21]
city=['hyd']
df1=pd.DataFrame(zip(name,age,city))
df1
name=['suresh']
age=[22]
city=['mumbai']
df2=pd.DataFrame(zip(name,age,city))
df2
s1=df1+df2
s1


0   1          2
0  rameshsuresh  43  hydmumbai

In [264]:
dict1={'name':['ramesh'],
       'age':[21],
       'city':['hyd']}
df1=pd.DataFrame(dict1)
df1
dict2={'name':['suresh'],
       'age':[22],
       'city':['mumbai']}
df2=pd.DataFrame(dict2)
df_combined = df1.append(df2, ignore_index=True)
df_combined

AttributeError: 'DataFrame' object has no attribute 'append'

In [9]:
import pandas as pd

# Create two DataFrames
df1 = pd.DataFrame({
    'A': [1, 2],
    'B': [3, 4]
})

df2 = pd.DataFrame({
    'A': [5, 6],
    'B': [7, 8]
})

# Use append to combine them
df_combined = df1.append(df2, ignore_index=True)
print(df_combined)


AttributeError: 'DataFrame' object has no attribute 'append'

In [11]:
import pandas as pd

# First dictionary and DataFrame
dict1 = {
    'name': ['ramesh'],
    'age': [21],
    'city': ['hyd']
}
df1 = pd.DataFrame(dict1)

# Second dictionary and DataFrame
dict2 = {
    'name': ['suresh'],
    'age': [22],
    'city': ['mumbai']
}
df2 = pd.DataFrame(dict2)

# Use pd.concat() instead of append()
df_combined = pd.concat([df1, df2], ignore_index=True)
print(df_combined)


     name  age    city
0  ramesh   21     hyd
1  suresh   22  mumbai
